version: "3.9"
services:
#  ddns:
#    image: "oznu/cloudflare-ddns:latest"
#    restart: always
#    env_file:
#      - .store/ddns.env
  mysql:
    image: "mysql:latest"
    restart: always
# for insternal use
#    expose:
#        "3306"
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/Pomodoro.sql:/docker-entrypoint-initdb.d/dump.sql
      - db:/var/lib/mysql
    cap_add:
      - SYS_NICE
    env_file:
      - .store/mysql.env
  nodejs:
    build: ./nodejs
    restart: always
    expose:
      - "3333"
    volumes:
      - ./nodejs/source:/source
      - ./nodejs/deploy:/root/deploy
      - .store/cert:/etc/nginx/cert:ro
      - ./nginx/html:/html
      - .store/ssh:/root/.ssh
    env_file:
      - .store/nodejs.env
    command: >
      sh -c "chmod +x /root/deploy/*.sh
      && /root/deploy/inotify_entrypoint.sh
      && exec nodemon app.js"
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - .store/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/njs_script:/etc/nginx/script
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/html2:/usr/share/nginx/html2
      - ./nginx/logs:/etc/nginx/logs
      - ./nodejs/deploy:/usr/share/nginx/node
      - .store/cert:/etc/nginx/cert:ro
    command: >
      bash -c "/root/inotify_entrypoint.sh
      && exec nginx -g 'daemon off;'"
volumes:
  db:


